more

diff --git a/vmctrl b/vmctrl
--- a/vmctrl
+++ b/vmctrl
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 qemu_bin="qemu-system-x86_64"
 qemu_flags="-nodefaults -enable-kvm"
 qemu_flags_run="-smp 4 -m 128 -kernel fudge -initrd fudge.img -vga std -serial stdio"
@@ -99,26 +101,24 @@ cmd_disconnect() {
     done
 }
 
-checkdisk() {
+cmd_disk_connect() {
     test -n "${1}" || error "Missing argument: id"
 
     disk="disks/node-$1-sda.qcow2"
-
-    test -f "${disk}" || error "File not found: ${disk}"
-
-    echo "${disk}"
-}
-
-cmd_disk_connect() {
-    disk=$(checkdisk "${1}")
+    device="/dev/nbd0"
 
     modprobe nbd
-    qemu-nbd --connect /dev/nbd0 "${disk}"
+    qemu-nbd --connect "${device}" "${disk}"
 }
 
 cmd_disk_disconnect() {
+    test -n "${1}" || error "Missing argument: id"
+
+    disk="disks/node-$1-sda.qcow2"
+    device="/dev/nbd0"
+
     modprobe nbd
-    qemu-nbd --disconnect /dev/nbd0
+    qemu-nbd --disconnect "${device}"
 }
 
 cmd_disk_create() {
@@ -133,42 +133,46 @@ cmd_disk_create() {
     echo "done"
 }
 
-cmd_disk_create_mbr() {
-    cmd_disk_connect "${1}"
-    echo -e "o\nw\n" | fdisk /dev/nbd0
-    mkfs.ext2 /dev/nbd0p1
-    cmd_disk_disconnect
-}
+cmd_disk_copy() {
+    test -n "${1}" || error "Missing argument: root"
+    test -n "${2}" || error "Missing argument: device"
 
-cmd_disk_create_ext2() {
-    cmd_disk_connect "${1}"
-    echo -e "n\n\n\n\n${2}\nw\n" | fdisk /dev/nbd0
-    mkfs.ext2 "${3}"
-    cmd_disk_disconnect
-}
-
-cmd_disk_generate() {
     mnt="disks/mnt"
 
-    cmd_disk_connect "${1}"
-    sleep 1
     mkdir -p "${mnt}"
     mount "${2}" "${mnt}"
 
-    if test -d "build"
+    if test -d "${1}"
     then
-        cp -r build/* "${mnt}"
+        cp -r "${1}" "${mnt}"
     fi
 
     umount "${mnt}"
-    cmd_disk_disconnect
 }
 
 cmd_disk_setup() {
-    cmd_disk_create_mbr "${1}"
-    cmd_disk_create_ext2 "${1}" "+1G" "/dev/nbd0p1"
-    cmd_disk_create_ext2 "${1}" "+512M" "/dev/nbd0p2"
-    cmd_disk_generate "${1}" "/dev/nbd0p1"
+    test -n "${1}" || error "Missing argument: id"
+
+    disk="disks/node-$1-sda.qcow2"
+    device="/dev/nbd0"
+    partuefi="${device}p1"
+    partboot="${device}p2"
+    partroot="${device}p3"
+
+    test -f "${disk}" || error "File not found: ${disk}"
+
+    cmd_disk_connect "${1}"
+    echo "label: dos" | sfdisk "${device}"
+    echo ",512M,0xEF,*" | sfdisk --append "${device}"
+    echo ",512M,0x83" | sfdisk --append "${device}"
+    echo ",1G,0x83" | sfdisk --append "${device}"
+    mkfs.fat -F 32 "${partuefi}"
+    mkfs.ext2 "${partboot}"
+    mkfs.ext2 "${partroot}"
+    cmd_disk_copy "fudge" "${partboot}"
+    cmd_disk_copy "initrd.cpio" "${partboot}"
+    cmd_disk_copy "build/." "${partroot}"
+    cmd_disk_disconnect "${1}"
 }
 
 cmd_help() {
